// Generated by https://quicktype.io

export interface App {
    id:           string;
    name:         string;
    stageRequest: StageRequest[];
    stage:        Stage[];
    startDate:    string;
    end:          string;
    tecnology:    Tecnology[];
    customer:     Customer[];
    hu:           Hu[];
}

export interface Customer {
    id:    number;
    name:  string;
    email: string;
    phone: number;
}

export interface Module {
    id:   number;
    description: string;
}

export interface Hu {
    id:          number;
    description: string;
    status:      Stage[];
    module: Module[];
}

export interface StageRequest {
    id:          number;
    description: string;
}

export interface Stage {
    id:          number;
    description: string;
}

export interface Tecnology {
    id:          number;
    description: string;
}

